default_velocity_scaling_factor: 0.35
default_acceleration_scaling_factor: 0.25

joint_limits:
  rail_joint: {has_velocity_limits: true, max_velocity: 0.4, has_acceleration_limits: false, has_position_limits: true, min_position: -2.325, max_position: 2.325}
  shoulder_pan_joint: {has_velocity_limits: true, max_velocity: 2.16, has_acceleration_limits: false}
  shoulder_lift_joint: {has_velocity_limits: true, max_velocity: 2.16, has_acceleration_limits: false}
  elbow_joint: {has_velocity_limits: true, max_velocity: 2.16, has_acceleration_limits: false}
  wrist_1_joint: {has_velocity_limits: true, max_velocity: 3.15, has_acceleration_limits: false}
  wrist_2_joint: {has_velocity_limits: true, max_velocity: 3.15, has_acceleration_limits: false}
  wrist_3_joint: {has_velocity_limits: true, max_velocity: 3.15, has_acceleration_limits: false}
  left_finger_joint: {has_velocity_limits: true, max_velocity: 0.05, has_acceleration_limits: false}
  right_finger_joint: {has_velocity_limits: true, max_velocity: 0.05, has_acceleration_limits: false}
